version: '2'
services:
    myaxe-app:
        image: myaxe
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://myaxe-mariadb:3306/myaxe
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    myaxe-mariadb:
        extends:
            file: mariadb.yml
            service: myaxe-mariadb
